export const CONTACT_LIST_REQUEST = 'CONTACT_LIST_REQUEST';
export const CONTACT_LIST_SUCCESS = 'CONTACT_LIST_SUCCESS';
export const CONTACT_LIST_FAIL = 'CONTACT_LIST_FAIL';

export const ADD_CONTACT_REQUEST = 'ADD_CONTACT_REQUEST';
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS';
export const ADD_CONTACT_FAIL = 'ADD_CONTACT_REQUEST';

export const UPDATE_CONTACT_REQUEST = 'UPDATE_CONTACT_REQUEST';
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
export const UPDATE_CONTACT_FAIL = 'UPDATE_CONTACT_FAIL';
export const UPDATE_CONTACT_RESET = 'UPDATE_CONTACT_RESET';


export const DETAILS_CONTACT_REQUEST = 'DETAILS_CONTACT_REQUEST';
export const DETAILS_CONTACT_SUCCESS = 'DETAILS_CONTACT_SUCCESS';
export const DETAILS_CONTACT_FAIL = 'DETAILS_CONTACT_FAIL';



export const REMOVE_CONTACT_SUCCESS = 'REMOVE_CONTACT_SUCCESS';
export const REMOVE_CONTACT_FAIL = 'REMOVE_CONTACT_FAIL';